# the host and port to run the proxy from, don't change this
client:
  host: "localhost"
  port: 2050

# the initial server to join
server:
  host: "54.235.235.140"
  port: 2050

# leave this empty if you don't know what you're doing
clientToken: ""

# the incoming and outgoing rc4 keys
keys:
  incoming: "c91d9eec420160730d825604e0"
  outgoing: "5a4d2016bc16dc64883194ffd9"

log:
  trace: True
  debug: True
  # use hex when printing packet bytes
  useHex: True
  packets:
    incoming: False
    outgoing: False